// <auto-generated />
namespace E_Invoice.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class mm2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mm2));
        
        string IMigrationMetadata.Id
        {
            get { return "202205251616215_mm2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
