// <auto-generated />
namespace E_Invoice.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _4545454 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_4545454));
        
        string IMigrationMetadata.Id
        {
            get { return "202206021846475_4545454"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
