<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <AssemblyName>E-Invoice.Desktop</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <OutputType>WinExe</OutputType>
    <UseWindowsForms>True</UseWindowsForms>
    <TargetFramework>net48</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>14.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <RootNamespace />
  </PropertyGroup>
  <ItemGroup>
    <None Remove="E-Invoice.Desktop.exe.licenses" />
    <EmbeddedResource Include="E-Invoice.Desktop.exe.licenses" LogicalName="E-Invoice.Desktop.exe.licenses" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.Core" />
    <ProjectReference Include="..\E-Invoice.Domain\E-Invoice.Domain.csproj" />
    <ProjectReference Include="..\E-Invoice.DAL\E-Invoice.DAL.csproj" />
    <Reference Include="DevComponents.DotNetBar2">
      <HintPath>..\Lib\DevComponents.DotNetBar2.dll</HintPath>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>..\Lib\Newtonsoft.Json.dll</HintPath>
    </Reference>
    <Reference Include="RestSharp">
      <HintPath>..\Lib\RestSharp.dll</HintPath>
    </Reference>
    <Reference Include="System.Data" />
    <Reference Include="MetroFramework">
      <HintPath>..\Lib\MetroFramework.dll</HintPath>
    </Reference>
    <Reference Include="IronXL">
      <HintPath>..\Lib\IronXL.dll</HintPath>
    </Reference>
    <Reference Include="EntityFramework">
      <HintPath>..\Lib\EntityFramework.dll</HintPath>
    </Reference>
    <Reference Include="EntityFramework.SqlServer">
      <HintPath>..\Lib\EntityFramework.SqlServer.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>



