<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>E-Invoice.DAL</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net48</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>14.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup>
    <RootNamespace />
  </PropertyGroup>
  <ItemGroup />
  <ItemGroup>
    <ProjectReference Include="..\E-Invoice.Domain\E-Invoice.Domain.csproj" />
    <Reference Include="EntityFramework">
      <HintPath>..\Lib\EntityFramework.dll</HintPath>
    </Reference>
    <Reference Include="EntityFramework.SqlServer">
      <HintPath>..\Lib\EntityFramework.SqlServer.dll</HintPath>
    </Reference>
    <Reference Include="System.Core" />
  </ItemGroup>
</Project>



