<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>E-Invoice.Domain</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net48</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>14.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="System.ComponentModel.DataAnnotations" />
    <Reference Include="Newtonsoft.Json">
      <HintPath>..\Lib\Newtonsoft.Json.dll</HintPath>
    </Reference>
    <Reference Include="RestSharp">
      <HintPath>..\Lib\RestSharp.dll</HintPath>
    </Reference>
    <Reference Include="Pkcs11Interop">
      <HintPath>..\Lib\Pkcs11Interop.dll</HintPath>
    </Reference>
    <Reference Include="System.Security" />
    <Reference Include="BouncyCastle.Crypto">
      <HintPath>..\Lib\BouncyCastle.Crypto.dll</HintPath>
    </Reference>
    <Reference Include="System.Core" />
    <Reference Include="Microsoft.CodeAnalysis">
      <HintPath>..\Lib\Microsoft.CodeAnalysis.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.CodeAnalysis.CSharp">
      <HintPath>..\Lib\Microsoft.CodeAnalysis.CSharp.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.CodeAnalysis.Scripting">
      <HintPath>..\Lib\Microsoft.CodeAnalysis.Scripting.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.CodeAnalysis.CSharp.Scripting">
      <HintPath>..\Lib\Microsoft.CodeAnalysis.CSharp.Scripting.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>


